markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true # HTMLブロック内のMarkdown解析を有効化

# Site settings
title: "宮原 渉 | Portfolio"
description: "研究実績まとめ"
url: "https://377H-Miru.github.io"
baseurl: ""

theme: jekyll-theme-minimal
